name: marketPlaceexplore
on: [push, workflow_dispatch]
jobs:
  market:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Get Node Version
        run: node -v
      - name: install dependencies
        run: yarn install
      - name: Run testcases
        run: yarn test
