name: TestAndDeploy
on: [workflow_dispatch]
jobs:
  testcase:
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v4
      - name: Install node js
        uses: actions/setup-node@v4 # This action sets up a Node.js environment
        with:
          node-version: "20"
      - name: Install Dependencies
        run: |
          yarn install
          yarn test
  deploy:
    needs: testcase #this job will start running once it testcase job will be done
    runs-on: ubuntu-latest
    steps:
      - name: clone the repo
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: yarn install
      - name: Build the project
        run: echo "Building Project"
